'''
This file contains the configuration class for this flask application.
This key,value pairs will later be the configuration for app (app.config["KEY"]).

About SESSION_COOKIE:
    Session cookie means that it will only send cookies back and forth
    if there is a secure HTTPS connection.
    Since the development and testing not going to be running over HTTPS, 
    change it to False.
'''
import os

class Config(object):
    SECRET_KEY = os.getenv('SECRET_KEY')

    # DATABASE
    DB_NAME = "production-db"
    DB_DRIVER = "ODBC Driver 11 for SQL Server"

    # DIRECTORY PATH
    DIR_UPLOAD = "C:/inetpub/wwwroot/SASKI/ATTACHMENT_SASKI"
    DIR_DOWNLOAD = "C:/inetpub/wwwroot/SASKI/static/public"

    # MAIL for email
    MAIL_SERVER = "smtprelay.kalbe.co.id"
    MAIL_PORT = 25
    MAIL_USE_TLS = False
    MAIL_USE_SSL = False

    # ROOT URL PREFIX
    ROOT_PREFIX = "/SASKI" 

    # SESSION COOKIES
    SESSION_COOKIE_SECURE = True
    
class ProductionConfig(Config):
    pass

class DevelopmentConfig(Config):
    # DATABASE
    DB_NAME = "development-db"
    DB_DRIVER = "ODBC Driver 17 for SQL Server"

    # DIRECTORY PATH
    DIR_UPLOAD = "C:/Users/SunnyLarosa/OneDrive - Bina Nusantara/01. Documents/Projects/nothing/user_upload"
    DIR_DOWNLOAD = "C:/Users/SunnyLarosa/OneDrive - Bina Nusantara/01. Documents/Projects/nothing/app/static/public/docs"

    # MAIL for email
    MAIL_SERVER = "smtp.gmail.com"
    MAIL_PORT = 465
    MAIL_USE_TLS = False
    MAIL_USE_SSL = True
    MAIL_USERNAME = "sunnylarosa121@gmail.com"
    MAIL_PASSWORD = "dabkvkumrtzvuzfw" # this is app password generated by google

    # SESSION COOKIES
    SESSION_COOKIE_SECURE = False